// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lijzllfvtitdcloxaiil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpanpsbGZ2dGl0ZGNsb3hhaWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNjU5MzQsImV4cCI6MjA2MDk0MTkzNH0.dCsHYQLMMceec1yIz9U2dKWfmDQ7P7XnCdjaZRzmcyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);